import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, AudioLines, ChevronLeft, ChevronRight, Clock3, Copyright, FileImage, Info, MapPin, Menu, Pause, Play, Search, Sparkles, X } from 'lucide-react'

const BASE = 'https://raw.githubusercontent.com/NucleoColectivo/Manrique-en-movimiento/main/img/'

type Photo = {
  id: string
  title: string
  year: string
  place: string
  family: string
  author: string
  before: string
  after: string
  animation: string
  testimony: string
  transcript: string
  map: string
  ai: { model: string; prompt: string; time: string; steps: string[] }
  rights: string
  credits: string
}

const photos: Photo[] = [
  { id:'manrique-01', title:'Una esquina, muchas memorias', year:'1940 · DEMO', place:'Manrique, Medellín', family:'Colección comunitaria', author:'Autoría por confirmar', before:'collage_1.png', after:'collage_1.png', animation:'banner_1.png', testimony:'“Aquí cada esquina tenía una historia.”', transcript:'Testimonio demostrativo. En la versión de archivo se incorporará el audio autorizado, su transcripción y contexto.', map:'La esquina', ai:{model:'Modelo de restauración / registro pendiente',prompt:'Restaurar sin inventar detalles; conservar textura, composición y señales de época.',time:'Registro pendiente',steps:['Digitalización','Restauración','Colorización','Animación sutil']},rights:'Uso sujeto a autorización de la colección y acuerdos comunitarios.',credits:'Manrique en Movimiento · Archivo vivo'},
  { id:'manrique-02', title:'Calles que cambian', year:'1950 · DEMO', place:'Manrique, Medellín', family:'Archivo barrial', author:'Autoría por confirmar', before:'collage_2.png', after:'collage_2.png', animation:'banner_3.png', testimony:'El paisaje cambia; la memoria permanece.', transcript:'Contenido demostrativo para mostrar la arquitectura de una ficha patrimonial.', map:'El camino', ai:{model:'Proceso IA documentado',prompt:'Recuperar información visual perdida evitando añadir elementos no presentes.',time:'Registro pendiente',steps:['Escaneo','Limpieza','Corrección','Movimiento']},rights:'Requiere verificación de derechos antes de publicación.',credits:'Manrique en Movimiento · Archivo vivo'},
  { id:'manrique-03', title:'La memoria también se hereda', year:'1970 · DEMO', place:'Comuna 3, Medellín', family:'Colección familiar', author:'Autoría por confirmar', before:'editorial_1.png', after:'editorial_1.png', animation:'editorial_2.png', testimony:'Una fotografía puede pasar de mano en mano y seguir hablando.', transcript:'Transcripción y audio comunitario se incorporarán con consentimiento.', map:'La casa', ai:{model:'Proceso IA documentado',prompt:'Animar únicamente microgestos y profundidad, sin cambiar identidad ni contexto.',time:'Registro pendiente',steps:['Preparación','Restauración','Profundidad','Animación']},rights:'Publicación condicionada a cesión/licencia acordada.',credits:'Manrique en Movimiento · Archivo vivo'},
]

const decadeData = [
  ['1940','Primeros relatos','banner_2.png'],['1950','Expansión urbana','banner_3.png'],['1960','Calles y familias','collage_1.png'],['1970','Transformaciones','collage_2.png'],['1980','Nuevas voces','collage_3.png'],['1990','Resiliencia','editorial_1.png'],['2000','Presente cercano','editorial_2.png'],['HOY','Memoria en construcción','banner_8.png'],
]

function App() {
  const [selected, setSelected] = useState<Photo | null>(null)
  const [textScale, setTextScale] = useState(1)
  const [menu, setMenu] = useState(false)
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => photos.filter(p => `${p.title} ${p.year} ${p.place}`.toLowerCase().includes(query.toLowerCase())), [query])

  useEffect(() => {
    document.documentElement.style.fontSize = `${16 * textScale}px`
    return () => { document.documentElement.style.fontSize = '16px' }
  }, [textScale])

  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(e => e.isIntersecting && e.target.classList.add('is-visible')), { threshold: .1 })
    document.querySelectorAll('.reveal').forEach(el => observer.observe(el))
    return () => observer.disconnect()
  }, [])

  return <div className="min-h-screen bg-paper text-ink">
    <header className="fixed top-0 left-0 right-0 z-40 border-b border-black/5 bg-paper/90 backdrop-blur-xl">
      <nav className="mx-auto flex max-w-[1380px] items-center justify-between gap-4 px-4 py-3 md:px-5" aria-label="Navegación principal">
        <a href="#inicio" className="shrink-0 font-display text-3xl font-black leading-[.72] tracking-[-.04em]">MANRIQUE,<span className="mt-1 block font-sans text-[.42rem] font-semibold tracking-[.25em] text-orange">MEMORIA EN MOVIMIENTO</span></a>
        <div className="hidden items-center gap-4 text-[.7rem] font-bold uppercase tracking-[.08em] lg:flex"><a href="#archivo">Archivo</a><a href="#historias">Historias</a><a href="#tiempo">Tiempo</a><a href="#mapa">Mapa</a><a href="#talleres">Talleres</a><a href="#participa">Participa</a></div>
        <div className="flex items-center gap-1"><button className="rounded-full border border-black/15 px-2 py-1 text-xs" onClick={()=>setTextScale(Math.max(.88,textScale-.06))} aria-label="Reducir tamaño de texto">A−</button><button className="rounded-full border border-black/15 px-2 py-1 text-xs" onClick={()=>setTextScale(Math.min(1.3,textScale+.06))} aria-label="Aumentar tamaño de texto">A+</button><button className="ml-1 rounded-full border border-black/15 p-2 lg:hidden" onClick={()=>setMenu(!menu)} aria-label="Abrir menú"><Menu size={16}/></button></div>
      </nav>
      {menu && <div className="border-t border-black/10 bg-paper px-5 py-4 lg:hidden"><div className="grid gap-3 text-sm font-bold uppercase">{['archivo','historias','tiempo','mapa','talleres','participa'].map(x=><a key={x} href={`#${x}`} onClick={()=>setMenu(false)}>{x}</a>)}</div></div>}
    </header>

    <main id="main">
      <section id="inicio" className="relative flex min-h-screen items-center overflow-hidden px-3 pb-8 pt-24 md:px-5">
        <div className="mx-auto w-full max-w-[1320px]">
          <div className="relative overflow-hidden rounded-[22px] md:rounded-[28px]"><img className="hero-breathe block w-full" src={`${BASE}banner_1.png`} alt="Composición principal de Manrique en Movimiento" fetchPriority="high"/><div className="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-paper via-paper/30 to-transparent"/>
            <div className="absolute bottom-5 left-5 max-w-[650px] md:bottom-12 md:left-12"><div className="mb-2 text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Archivo vivo · Comuna 3 · Medellín</div><h1 className="font-display text-[4.6rem] font-black uppercase leading-[.72] tracking-[-.045em] sm:text-[6rem] md:text-[8rem]">La memoria<br/>está en movimiento.</h1><p className="mt-5 max-w-xl text-base md:text-lg">Fotografías, voces, lugares y nuevas tecnologías se encuentran para contar la memoria de Manrique desde la comunidad.</p><a href="#archivo" className="mt-5 inline-flex items-center gap-2 rounded-full bg-blue px-5 py-3 font-bold text-white">Explorar el archivo <ArrowRight size={17}/></a></div>
          </div>
        </div>
      </section>

      <section className="bg-ink py-28 text-white md:py-36"><div className="reveal mx-auto grid max-w-[1380px] gap-12 px-5 md:grid-cols-[.9fr_1.5fr] md:items-center"><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Manifiesto</div><h2 className="mt-2 font-display text-[4rem] font-black uppercase leading-[.76] tracking-[-.045em] md:text-[7rem]">Las fotografías<br/>guardan <span className="text-orange">recuerdos.</span></h2></div><p className="text-3xl leading-[.98] md:text-6xl">Juntos podemos <em className="text-gold not-italic">devolverles la vida</em> sin borrar sus huellas. La IA es una herramienta; la memoria pertenece a la comunidad.</p></div></section>

      <section id="archivo" className="py-24 md:py-32"><div className="mx-auto max-w-[1380px] px-5"><SectionHead eyebrow="01 · Archivo fotográfico" title={<>Un archivo<br/>que <span className="text-orange">respira.</span></>} text="Cada imagen es un objeto patrimonial. La ficha conserva procedencia, contexto, intervención, testimonio, territorio, IA, créditos y derechos."/>
        <div className="mb-7 flex flex-wrap items-center justify-between gap-4"><label className="flex items-center gap-2 rounded-full border border-black/15 bg-white px-4 py-2 text-sm"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en el archivo…" className="w-52 bg-transparent outline-none" aria-label="Buscar fotografías"/></label><span className="text-xs uppercase tracking-widest text-black/50">{filtered.length} objetos visibles</span></div>
        <div className="grid gap-5 md:grid-cols-3">{filtered.map(p=><button key={p.id} onClick={()=>setSelected(p)} className="reveal overflow-hidden rounded-3xl border border-black/10 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-2xl"><img src={`${BASE}${p.after}`} alt={p.title} className="aspect-[4/3] w-full object-cover" loading="lazy"/><div className="p-6"><div className="text-[.65rem] font-extrabold uppercase tracking-[.18em] text-orange">{p.year}</div><h3 className="mt-2 font-display text-4xl font-black uppercase leading-[.82]">{p.title}</h3><p className="mt-3 text-sm text-black/60">{p.place} · {p.family}</p><span className="mt-4 inline-flex items-center gap-2 font-bold text-blue">Abrir ficha patrimonial <ArrowRight size={15}/></span></div></button>)}</div>
      </div></section>

      <section id="historias" className="bg-paper py-20 md:py-28"><div className="mx-auto max-w-[1380px] px-5"><SectionHead eyebrow="02 · Historias" title={<>Voces que<br/><span className="text-blue">permanecen.</span></>} text="La fotografía se completa cuando alguien la recuerda. Audio, transcripción, subtítulos y contexto acompañan cada objeto."/><div className="grid gap-5 md:grid-cols-[1.15fr_.85fr]"><Story image="editorial_1.png" title="Aquí cada esquina tenía una historia."/><Story image="editorial_2.png" title="El barrio también se recuerda con los ojos."/></div></div></section>

      <section id="tiempo" className="py-24 md:py-32"><div className="mx-auto max-w-[1380px] px-5"><SectionHead eyebrow="03 · Línea del tiempo" title={<>Manrique<br/>por <span className="text-teal">décadas.</span></>} text="Selecciona una década para recorrer fotografías, relatos, sonidos y transformaciones del barrio."/><Timeline/></div></section>

      <section id="mapa" className="py-20 md:py-28"><div className="mx-auto max-w-[1380px] px-5"><SectionHead eyebrow="04 · Mapa de memoria" title={<>Caminar<br/>el <span className="text-orange">barrio.</span></>} text="Una cartografía afectiva donde cada punto podrá abrir una fotografía, una voz, un video y una historia."/><div className="relative min-h-[520px] overflow-hidden rounded-3xl bg-[#d9cfbf]"><img src={`${BASE}collage_3.png`} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-40 sepia-[.15]"/><div className="absolute inset-0 bg-gradient-to-r from-paper/95 via-paper/25 to-transparent"/><div className="absolute left-7 top-7 max-w-sm"><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Cartografía afectiva</div><h3 className="mt-2 font-display text-5xl font-black uppercase leading-[.8]">Los lugares también recuerdan.</h3><p className="mt-4 text-sm">Los nodos son conceptuales en esta versión. En producción se conectarán con coordenadas reales del archivo.</p></div>{[['La esquina','38%','48%'],['La casa','59%','31%'],['El camino','70%','63%'],['La cancha','47%','74%']].map(([n,l,t])=><button key={n} onClick={()=>{const p=photos.find(x=>x.map===n)||photos[0];setSelected(p)}} className="absolute h-6 w-6 rounded-full bg-orange shadow-[0_0_0_8px_rgba(198,91,42,.18)]" style={{left:l,top:t}} aria-label={`Abrir memoria: ${n}`}/>)}</div></div></section>

      <section className="py-20 md:py-28"><div className="mx-auto max-w-[1380px] px-5"><SectionHead eyebrow="05 · Documental" title={<>El pasado<br/>camina <span className="text-orange">con nosotros.</span></>} text="La narrativa visual se convierte en experiencia audiovisual: trailer, documental, making-of y storyboard."/><div className="overflow-hidden rounded-3xl bg-white"><img src={`${BASE}banner_4.png`} alt="Banner documental de Manrique en Movimiento" className="w-full" loading="lazy"/></div></div></section>

      <section id="talleres" className="py-20 md:py-28"><div className="mx-auto max-w-[1380px] px-5"><SectionHead eyebrow="06 · Talleres + IA" title={<>Aprender<br/><span className="text-blue">haciendo.</span></>} text="Restaurar, animar, documentar y compartir. La tecnología se presenta de forma transparente y crítica."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['01','Digitalizar','Conservar el original y registrar procedencia.'],['02','Restaurar','Intervenir sin ocultar qué fue reconstruido.'],['03','Animar','Movimiento sutil, narrativo y claramente identificado.'],['04','Documentar','Modelo, prompt, herramienta, autoría y licencia.']].map(([n,t,x])=><article key={n} className="border-t-[5px] border-orange bg-white p-6"><b className="font-display text-5xl text-blue">{n}</b><h3 className="mt-2 font-display text-3xl font-black uppercase leading-[.85]">{t}</h3><p className="mt-3 text-sm text-black/60">{x}</p></article>)}</div><div className="mt-5 overflow-hidden rounded-3xl"><img src={`${BASE}collage_6.png`} alt="Composición gráfica de taller y memoria" className="w-full" loading="lazy"/></div></div></section>

      <section id="participa" className="py-20 md:py-28"><div className="mx-auto max-w-[1380px] px-5"><div className="reveal grid gap-8 rounded-3xl bg-blue p-8 text-white md:grid-cols-[1.2fr_.8fr] md:p-14"><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-gold">Convocatoria permanente</div><h2 className="mt-2 font-display text-6xl font-black uppercase leading-[.76] md:text-8xl">Tu álbum también hace parte de la historia.</h2><p className="mt-5 max-w-xl">El archivo crece con las fotografías y relatos de quienes han vivido Manrique.</p></div><div className="self-end"><div className="text-xs font-bold uppercase">Comparte una memoria por WhatsApp</div><div className="font-display text-5xl font-black text-gold md:text-6xl">+57 319 624 2779</div><a href="https://wa.me/573196242779" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 font-bold text-blue">Compartir una memoria <ArrowRight size={17}/></a></div></div></div></section>
    </main>

    <footer className="bg-ink py-20 text-white"><div className="mx-auto max-w-[1380px] px-5"><div className="grid gap-10 md:grid-cols-[1.4fr_.6fr_.6fr]"><div className="font-display text-7xl font-black uppercase leading-[.72]">Manrique,<br/>memoria<br/>en movimiento.</div><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Explorar</div><p>Archivo</p><p>Historias</p><p>Tiempo</p><p>Talleres</p></div><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Principio</div><p>La IA es una herramienta.</p><p>La memoria pertenece a la comunidad.</p></div></div><div className="mt-12 border-t border-white/10 pt-4 text-xs text-white/50">Manrique en Movimiento · React + Vite + TypeScript + Tailwind · Archivo visual comunitario</div></div></footer>

    {selected && <ArchiveDrawer photo={selected} onClose={()=>setSelected(null)}/>} 
  </div>
}

function SectionHead({eyebrow,title,text}:{eyebrow:string,title:React.ReactNode,text:string}) { return <div className="reveal mb-12 grid gap-8 md:grid-cols-[1fr_1.1fr] md:items-end"><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">{eyebrow}</div><h2 className="mt-2 font-display text-[4.5rem] font-black uppercase leading-[.76] tracking-[-.045em] md:text-[7rem]">{title}</h2></div><p className="max-w-2xl text-lg text-black/60">{text}</p></div> }
function Story({image,title}:{image:string,title:string}) { return <article className="group relative min-h-[480px] overflow-hidden rounded-3xl bg-black"><img src={`${BASE}${image}`} alt={title} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.02]" loading="lazy"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 to-transparent p-7 pt-32 text-white"><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-gold">Relato · Archivo</div><h3 className="mt-2 font-display text-5xl font-black uppercase leading-[.8]">{title}</h3><button className="mt-5 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 font-bold text-ink">Abrir historia <ArrowRight size={15}/></button></div></article> }
function Timeline(){ const [i,setI]=useState(0); const d=decadeData[i]; return <div><div className="flex gap-2 overflow-auto pb-3" role="tablist">{decadeData.map((x,j)=><button key={x[0]} onClick={()=>setI(j)} className={`min-w-[125px] rounded-2xl border px-4 py-3 text-left ${i===j?'border-orange bg-orange text-white':'border-black/10 bg-white'}`}><span className="text-xs font-bold uppercase">{x[0]}</span><b className="mt-1 block font-display text-4xl leading-none">{x[0]==='HOY'?'∞':x[0].slice(-2)}</b></button>)}</div><div className="mt-5 grid overflow-hidden rounded-3xl border border-black/10 bg-white md:grid-cols-2"><div className="p-7 md:p-10"><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">{d[0]} · DEMO</div><h3 className="mt-2 font-display text-6xl font-black uppercase leading-[.76]">{d[1]}</h3><p className="mt-5 text-black/60">Fotografías familiares, documentos, sonidos y relatos que reconstruyen los capítulos del archivo.</p></div><img src={`${BASE}${d[2]}`} alt={`Pieza visual de la década ${d[0]}`} className="min-h-[330px] w-full object-cover" loading="lazy"/></div></div> }

function ArchiveDrawer({photo,onClose}:{photo:Photo,onClose:()=>void}) { const [tab,setTab]=useState<'ficha'|'comparar'|'animacion'|'testimonio'|'mapa'|'ia'|'derechos'>('ficha'); const [pos,setPos]=useState(50); const tabs=[['ficha','Ficha'],['comparar','Antes / Después'],['animacion','Animación'],['testimonio','Testimonio'],['mapa','Mapa'],['ia','IA'],['derechos','Créditos y derechos']] as const; return <div className="fixed inset-0 z-50 bg-black/75 p-0 md:p-5" role="dialog" aria-modal="true" aria-label={`Ficha patrimonial: ${photo.title}`}><div className="mx-auto flex h-full max-w-[1280px] flex-col overflow-hidden bg-paper md:rounded-3xl"><header className="flex items-center justify-between border-b border-black/10 bg-paper px-5 py-4"><div><div className="text-[.62rem] font-extrabold uppercase tracking-[.2em] text-orange">Objeto patrimonial · {photo.id}</div><h2 className="font-display text-4xl font-black uppercase leading-[.8]">{photo.title}</h2></div><button onClick={onClose} className="rounded-full border border-black/15 p-2" aria-label="Cerrar ficha"><X size={20}/></button></header><div className="flex gap-2 overflow-auto border-b border-black/10 px-5 py-3">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${tab===id?'bg-blue text-white':'bg-black/5'}`}>{label}</button>)}</div><div className="min-h-0 flex-1 overflow-y-auto p-5 md:p-8">{tab==='ficha'&&<Ficha photo={photo} setTab={setTab}/>} {tab==='comparar'&&<Compare photo={photo} pos={pos} setPos={setPos}/>} {tab==='animacion'&&<Animation photo={photo}/>} {tab==='testimonio'&&<Testimony photo={photo}/>} {tab==='mapa'&&<MapTab photo={photo}/>} {tab==='ia'&&<AITab photo={photo}/>} {tab==='derechos'&&<Rights photo={photo}/>}</div></div></div> }

function Ficha({photo,setTab}:{photo:Photo,setTab:(x:any)=>void}){return <div className="grid gap-8 md:grid-cols-[1.2fr_.8fr]"><div><img src={`${BASE}${photo.after}`} alt={photo.title} className="w-full rounded-2xl"/><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Meta icon={<Clock3/>} label="Fecha" value={photo.year}/><Meta icon={<MapPin/>} label="Lugar" value={photo.place}/><Meta icon={<FileImage/>} label="Familia" value={photo.family}/><Meta icon={<Info/>} label="Autor" value={photo.author}/></div></div><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Contexto</div><h3 className="mt-2 font-display text-5xl font-black uppercase leading-[.8]">La fotografía como puerta.</h3><p className="mt-5 text-black/60">Esta ficha funciona como núcleo del objeto: de aquí se puede recorrer su transformación, animación, memoria oral, territorio, proceso IA y condiciones de uso.</p><div className="mt-6 flex flex-wrap gap-2">{['original','restauración','memoria oral','territorio','IA'].map(x=><span key={x} className="rounded-full bg-black/5 px-3 py-1 text-xs font-bold">{x}</span>)}</div><button onClick={()=>setTab('comparar')} className="mt-7 inline-flex items-center gap-2 rounded-full bg-blue px-5 py-3 font-bold text-white">Ver antes / después <ArrowRight size={16}/></button></div></div>}
function Meta({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="rounded-xl border border-black/10 bg-white p-3"><div className="flex items-center gap-1 text-[.6rem] font-bold uppercase text-black/45">{icon}{label}</div><div className="mt-1 text-xs font-bold">{value}</div></div>}
function Compare({photo,pos,setPos}:{photo:Photo,pos:number,setPos:(x:number)=>void}){return <div><div className="mb-6"><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Conservación visual</div><h3 className="font-display text-6xl font-black uppercase leading-[.78]">Antes / Después</h3><p className="mt-3 text-black/60">El archivo conserva el original y hace explícita la intervención.</p></div><div className="relative h-[55vh] min-h-[360px] overflow-hidden rounded-3xl bg-black"><img src={`${BASE}${photo.before}`} alt="Estado original" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 overflow-hidden" style={{clipPath:`inset(0 0 0 ${pos}%)`}}><img src={`${BASE}${photo.after}`} alt="Estado intervenido" className="h-full w-full object-cover"/></div><div className="absolute bottom-5 left-5 rounded-full bg-black/70 px-3 py-1 text-xs text-white">Original</div><div className="absolute bottom-5 right-5 rounded-full bg-blue/90 px-3 py-1 text-xs text-white">Intervenido</div><div className="absolute bottom-0 top-0 w-0.5 bg-white" style={{left:`${pos}%`}}/><input aria-label="Comparar original e intervención" type="range" min="0" max="100" value={pos} onChange={e=>setPos(+e.target.value)} className="absolute inset-0 h-full w-full cursor-ew-resize opacity-0"/></div></div>}
function Animation({photo}:{photo:Photo}){const [play,setPlay]=useState(false);return <div className="grid gap-8 md:grid-cols-[1.2fr_.8fr]"><div className="overflow-hidden rounded-3xl bg-black"><img src={`${BASE}${photo.animation}`} alt="Animación fotográfica" className={`w-full transition duration-[6000ms] ${play?'scale-110 -translate-y-2':'scale-100'}`}/></div><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Movimiento responsable</div><h3 className="mt-2 font-display text-6xl font-black uppercase leading-[.78]">Las fotografías vuelven a respirar.</h3><p className="mt-5 text-black/60">La animación es una interpretación. No debe presentarse como registro documental ni inventar acontecimientos.</p><button onClick={()=>setPlay(!play)} className="mt-6 inline-flex items-center gap-2 rounded-full bg-blue px-5 py-3 font-bold text-white">{play?<Pause size={16}/>:<Play size={16}/>} {play?'Pausar':'Reproducir'} movimiento</button></div></div>}
function Testimony({photo}:{photo:Photo}){return <div className="mx-auto max-w-4xl"><AudioLines size={36} className="text-orange"/><blockquote className="mt-5 font-display text-6xl font-black leading-[.78]">“{photo.testimony.replaceAll('“','').replaceAll('”','')}”</blockquote><div className="mt-10 rounded-2xl bg-white p-6"><div className="text-[.65rem] font-extrabold uppercase tracking-[.18em] text-orange">Transcripción</div><p className="mt-3">{photo.transcript}</p></div></div>}
function MapTab({photo}:{photo:Photo}){return <div className="grid gap-8 md:grid-cols-[1fr_1fr]"><div className="relative min-h-[420px] overflow-hidden rounded-3xl bg-[#d9cfbf]"><img src={`${BASE}collage_3.png`} alt="Mapa conceptual del territorio" className="absolute inset-0 h-full w-full object-cover opacity-45"/><div className="absolute inset-0 bg-paper/25"/><div className="absolute left-[48%] top-[48%] h-6 w-6 rounded-full bg-orange shadow-[0_0_0_8px_rgba(198,91,42,.18)]"/></div><div><div className="text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange">Lugar asociado</div><h3 className="mt-2 font-display text-6xl font-black uppercase leading-[.78]">{photo.map}</h3><p className="mt-5 text-black/60">En la versión productiva, este nodo tendrá coordenadas, precisión geográfica, fotografías relacionadas y recorrido narrativo.</p></div></div>}
function AITab({photo}:{photo:Photo}){return <div><div className="flex items-center gap-2 text-[.68rem] font-extrabold uppercase tracking-[.2em] text-orange"><Sparkles size={14}/> Trazabilidad IA</div><div className="mt-4 grid gap-4 md:grid-cols-3"><Meta icon={<Sparkles/>} label="Modelo" value={photo.ai.model}/><Meta icon={<Clock3/>} label="Tiempo" value={photo.ai.time}/><Meta icon={<FileImage/>} label="Etapas" value={photo.ai.steps.join(' · ')}/></div><div className="mt-5 rounded-2xl bg-ink p-6 text-white"><div className="text-xs font-bold uppercase text-gold">Prompt registrado</div><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-relaxed text-white/80">{photo.ai.prompt}</pre></div></div>}
function Rights({photo}:{photo:Photo}){return <div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl bg-white p-7"><Copyright className="text-orange"/><h3 className="mt-4 font-display text-5xl font-black uppercase leading-[.8]">Créditos</h3><p className="mt-4 text-black/60">{photo.credits}</p><p className="mt-3 text-sm">Autoría: {photo.author}</p></div><div className="rounded-2xl bg-white p-7"><h3 className="font-display text-5xl font-black uppercase leading-[.8]">Derechos y consentimiento</h3><p className="mt-4 text-black/60">{photo.rights}</p><div className="mt-5 rounded-xl bg-orange/10 p-4 text-sm font-semibold">La ficha debe impedir publicar una fotografía sin haber registrado su procedencia y condición de uso.</div></div></div>}

export default App
